server:
  port: ${PORT:8080}

vtb-api:
  key: ${VTB_API_KEY}
  host: https://gw.hackathon.vtb.ru/vtb/hackathon
  endpoint:
    car-recognize: car-recognize

youtube-api:
  key: ${YOUTUBE_API_KEY}
  host: https://www.googleapis.com/youtube/v3
  endpoint:
    search: search
